version: 1
disable_existing_loggers: False
formatters:
    simple: 
        format: "%(levelname)s - %(name)s - %(asctime)s - %(module)s.%(funcName)s - %(message)s"
handlers: 
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        
    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: test.log
        maxBytes: 1024
        backupCount: 5
        encoding: "utf8"
        

    stream:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        
    file_write:
        class: concurrent_log_handler.ConcurrentRotatingFileHandler
        formatter: simple
        level: INFO
        filename:  G:\spider_learn\spider_learn\proxy_pool_new\proxy_pool_new\logs\jess3.log
        maxBytes: 1024*1024*5
        backupCount: 10
        mode: a
        
    
      


loggers:
    fileLogger:
        level: DEBUG
        handlers: [console, info_file_handler]
        propagate: no
    
    utils:
        level: INFO
        handlers: [stream,file_write]
        propagate: no

    getter:
        level: INFO
        handlers: [stream,file_write]
        propagate: no


    db:
        level: INFO
        handlers: [stream,file_write]
        propagate: no

    test:
        level: INFO
        handlers: [stream,file_write]
        propagate: no

    crawler:
        level: INFO
        handlers: [stream,file_write]
        propagate: no
    
roots:
    level: DEBUG
    handlers: [console]
    propagate: true